### ISSUE TITLE
Player URL does not work, if player name has spaces

### ISSUE THREAD

**Issue by larsi-org** [plasticlobster/kol-skills#2]
The script claims, that the skills can be looked at this URL:
http://www.plasticlobster.com/kolshow.php?user=End+of+Time

Which does not work.  The user name is 'End of Time'.
It does work if the user name doesn't have space though.

**Comment by plasticlobster** [comment]
Looking into it to see if it's a mafia script thing or server-side thing. I'll let you know what I find. Thanks for reporting.

**Comment by plasticlobster** [comment]
Found the issue. Use this link in the mean time, and I'll push out a fix:
http://www.plasticlobster.com/kolshow.php?user=End%2Bof%2BTime

**Comment by plasticlobster** [comment]
Fix is pushed out. Basically, KoLMafia was sending out the user name with +'s instead of spaces. The backend server was saving the information with the +'s, then when you went to the URL, the +'s were being turned into spaces.

No update necessary to the mafia script. I forced it to interpret +'s properly when you're visiting the URL, and now it should display nicely.

I'll close out the issue, but definitely comment or open a new one if you run into anything else.

**Comment by larsi-org** [comment]
Works - thanks!
